# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-playbook-run
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-play
  template:
    metadata:
      labels:
        app: ansible-play
    spec:
      containers:
      - name: ansible-play-run
        image: vithalangadidocker/my-ansible
      #   env:
      #   - name: KUBECONFIG
      #     value: "/kubeconfig/config"
      #   volumeMounts:
      #   - name: kubeconfig
      #     mountPath: "/kubeconfig"
      # volumes:
      # - name: kubeconfig
      #   configMap:
      #     name: kubeconfig
